site_name: Hyrapi Documentation
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: teal
  icon:
    repo: null
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - navigation.instant

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg

repo_url: https://github.com/hwisnu222/hyrapi # opsional
